### ISSUE TITLE
Where do I place the `.scss-lint.yml` file

### ISSUE THREAD

**Issue by amitrai4code** [ivantsepp/codeclimate-scss-lint#10]
I have a rails application and added the `.scss-lint.yml` inside `config/code_climate` folder.

I added the `.codeclimate.yml` to repository root but I am not able to figure out how I can link the scss linter engine to the `.scss-lint.yml` inside the `config/code_climate` folder.  There seems to be no documentation for this in this repo.

**Comment by ivantsepp** [comment]
I believe you can add a `config` attribute inside your `.codeclimate.yml` which points to the scss-lint config file location. An example for `.codeclimate.yml` would look like:

```
---
engines:
  scss-lint:
    enabled: true
    config: 'config/code_climate/.scss-lint.yml'
```

Let me know if that works! I also welcome any PR to add additional documentation 😄
