### ISSUE TITLE
Configuration from repository is not applied

### ISSUE THREAD

**Issue by leobut** [ivantsepp/codeclimate-scss-lint#17]
Hi, I have a JavaScript project, where I build my code using grunt.

I use sass-lint via grunt and have a configuration for it. When I run this locally or on travis, sass-lint understands my configuration correctly, but on codeclimate it seems to ignore my config.

Can you tell me what is wrong? Thanks!

**My config:**
(Can also be found here: [geocachingUtils/.scss-lint.yml](https://github.com/ControlTheBit/geocachingUtils/blob/master/.scss-lint.yml) )
File name: `.scss-lint.yml`
```
rules:
  # Consistency Rules
  extends-before-mixins: 1
  extends-before-declarations: 1
  mixins-before-declarations: 1
  # Require an empty line between blocks
  empty-line-between-blocks: 0
  no-empty-rulesets: 1
  final-newline: 0
  no-ids: 0
  indentation: 0
  leading-zero: 0
  name-format: 0
  nesting-depth: 0
  placeholder-in-extend: 1
  property-sort-order: 0
  property-spelling: 0
  shorthand: 0
  one-declaration-per-line: 1
  single-line-per-selector: 1
  space-after-comma: 1
  # Space surrounding colons
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-between-parens: 1
  trailing-semicolon: 1
  class-name-format:
    - 1
    -
      convention: 'camelcase'
      allow-leading-underscore: false
```
